### ISSUE TITLE
overwriting the default handler

### ISSUE THREAD

**Issue by ostat** [gmelillo/docker-dehydrated-lexicon#10]
Is there an example of how to overwrite the default handler?

I am using the docker container from github.

I saw this comment in the dockerfile
```
# Default handler used by the docker compose.
# it is possible to overwire it mounting a new one and seting the new path on this variable.
ENV 'DEHYDRATED_HANDLER' '/dehydrated/hooks/dehydrated.default.sh'
```

So I added this config to the docker compose file
```
    volumes:
      - ./vol/dehydrated.custom.sh:/dehydrated/hooks/dehydrated.default.sh
    environment:
      DEHYDRATED_HANDLER: /dehydrated/accounts/dehydrated.custom.sh
```

But this results in this error for me
```
#
# !! WARNING !! No main config file found, using default config!
#
env: can't execute 'bash': No such file or directory
ERROR: Please check your hook script, it should exit cleanly without doing anything on unknown/new hooks.
env: can't execute 'bash': No such file or directory
exit_hook returned with non-zero exit code!
```

If I just map the file and connect to the container while its running i can see that the file is there. I tried setting the permissions to 777 and root:root.
